Dev
WildCodeSchool-2024-02/JS-lyon-0224-P2-ivory pull request #140
Opened 2024-04-26 08:54 UTC by MaxAnxxi

Second big Pull Request towards main

US that have been added : 

US09 - Bloc quiz ( display none for now , waiting for more content that should be done during the day , CSS to make it clean is also job in progress ) 
US35 - Home button to come back to the menu in the NavBar
US37 - Button to switch theme between dark/light with a memo so it doesn't rerender all the time
US33 - API Fetched so we have the video from the API in the video section
US34 - Videos are finally responsive , you can launch them and the full screen is also doable on the videos
US30 - React page is done , content added ( can be modified during the day with a quiz section ) 
US32 - CSS page done , content added ( can be modified during the day with a quiz section ) 
US36 - Organizing formation button on the Homepage to fit the routes and the corresponding pages
US31 - Page Javascript done , content added ( can be modified during the day with a quiz section ) 

More content might be coming during the day

2024-04-26 09:45 UTC, HazeFury commented on client/src/components/formation/Formation.jsx
>    const [show, setShow] = useState(false);
A priori, vous avez retiré la ligne suivante : 
{show === true ? <Lesson /> : null}

du coup je ne vois plus d'utilisation / utilité a garder le state "show" et la fonction handleClick.
Donc à supprimer ^^

2024-04-26 09:52 UTC, HazeFury commented on client/src/components/navbar/NavbarStyle.module.css
> +  /* background: #fffcf4; */
Pourquoi c'est commenté ça ?? 
Si ce n'est pas utilisé => vous le retirez !

2024-04-26 09:52 UTC, MaxAnxxi commented on client/src/components/formation/Formation.jsx
>    const [show, setShow] = useState(false);
C'est vrai que j'y ai penser et puis c'est passé à la trappe derrière , je m'en occupe

2024-04-26 09:55 UTC, HazeFury commented on client/src/components/quiz/Quiz.jsx
C'est ça le bloc Quizz du coup ??

2024-04-26 09:56 UTC, MaxAnxxi commented on client/src/components/quiz/Quiz.jsx
Oui

2024-04-26 13:46 UTC, HazeFury commented on client/src/components/video_search/VideoSearch.jsx
bien sympa le slider avec les vidéos 💯

2024-04-26 14:27 UTC, wildmatthieu requested changes

2024-04-26 14:27 UTC, wildmatthieu commented on client/src/assets/React App.png
un espace dans le nom de fichier 
=> à éviter

Renommer le fichier en remplaçant l'espace par un _

2024-04-26 14:27 UTC, wildmatthieu commented on client/src/assets/React logo js.jpg
deux espaces dans le nom de fichier
=> à éviter

Renommer le fichier en remplaçant l'espace par un _

2024-04-26 14:27 UTC, wildmatthieu commented on client/src/assets/react structure.png
un espace dans le nom de fichier
=> à éviter

Renommer le fichier en remplaçant l'espace par un _

2024-04-26 14:27 UTC, wildmatthieu commented on client/src/assets/react use for.png
espaces dans le nom de fichier
=> à éviter

Renommer le fichier en remplaçant les espaces par un _

2024-04-26 15:03 UTC, HazeFury commented on client/src/pages/homepage/homePageStyle.module.css
Si le fichier ne vous sert pas, à supprimer.

2024-04-26 15:14 UTC, HazeFury approved these changes
Bon bah c'est du bon boulot dans l'ensemble, bravo à vous 👍 💯 

Quelques petits changement mineures à faire.

Sinon en lancant votre projet en local, j'ai trouvé quelques coquilles : 

- quand on ouvre le menu sur mobile et qu'on repasse en desktop ça pète les icônes
- sur mobile quand on ouvre le menu burger et qu'on scroll la croix pour fermer le menu ne suit pas 
- les snippets de code git dépasse sur la navbar

2024-04-29 07:15 UTC, wildmatthieu approved these changes

2024-04-29 07:15 UTC, wildmatthieu commented
GG à vous ! :D

2024-04-29 07:15 UTC, merged